In [1]:
import pandas as pd
import numpy as np

In [11]:
train=pd.read_csv("Train (2).csv")
fhc=pd.read_csv("First_Health_Camp.csv")
shc=pd.read_csv("Second_Health_Camp.csv")
thc=pd.read_csv("Third_Health_Camp.csv")
hc_details=pd.read_csv("Health_Camp_Detail.csv")
patient=pd.read_csv("Patient_Details.csv")
test=pd.read_csv("Test (2).csv")
ss=pd.read_csv("Sample_Submission (1).csv")
trainav=pd.read_csv("Train.csv")

In [13]:
test.sort_values("Patient_ID").head(5)
train
#test.merge(trainav,on=["Patient_ID","Health_Camp_ID"],how="left")

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  \
0          526927            6570          14/05/05     0     0     0     0   
1          510379            6534          26/05/06     0     0     0     0   
2          520968            6557          07/01/04     0     0     0     0   
3          507625            6535          12/02/04     0     0     0     0   
4          502611            6581          14/03/04     0     0     0     0   
...           ...             ...               ...   ...   ...   ...   ...   
52689      528062            6529          03/03/06     0     0     0     0   
52690      513331            6546          10/01/04     0     0     0     0   
52691      486727            6523          30/04/05     0     0     0     0   
52692      515312            6523          06/09/05     0     0     0     0   
52693      488938            6562          11/02/05     0     0     0     0   

       Var5  outcome  
0         0        0  
1         0        1  
2         0        1  
3         0        0  
4         0        0  
...     ...      ...  
52689     0        1  
52690     0        0  
52691     0        1  
52692     0        1  
52693     0        0  

[52694 rows x 9 columns]

In [709]:
train.merge(patient,on=["Patient_ID"],how="left").corr()["outcome"]

Patient_ID        -0.007473
Health_Camp_ID    -0.154757
Var1               0.048210
Var2               0.034520
Var3               0.012551
Var4               0.034137
Var5               0.064288
outcome            1.000000
Online_Follower    0.050614
LinkedIn_Shared    0.056983
Twitter_Shared     0.045460
Facebook_Shared    0.039949
Name: outcome, dtype: float64

In [690]:
#train.merge(fhc,on=["Patient_ID","Health_Camp_ID"],how="left").sort_values("Patient_ID")
test.merge(hc_details,on="Health_Camp_ID",how="left")
test.merge(patient,on="Patient_ID",how="left")

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  \
0          507518            6529          02/04/06     0     0     0     0   
1          516180            6570          13/05/05     0     0     0     0   
2          507204            6537          16/01/07     0     0     0     0   
3          505815            6578          27/07/05     0     0     0     0   
4          501809            6542          22/07/05     0     0     0     0   
...           ...             ...               ...   ...   ...   ...   ...   
22579      521837            6539          02/09/04     0     0     0     0   
22580      490592            6532          24/05/05     1     0     0     0   
22581      499464            6538          05/02/04     0     0     0     0   
22582      525833            6562          19/03/05     0     0     0     0   
22583      506132            6540          16/10/04     8     2     0     1   

       Var5  Online_Follower  LinkedIn_Shared  Twitter_Shared  \
0         0                0                0               0   
1         0                0                0               0   
2         0                0                0               0   
3         0                0                0               0   
4         0                0                0               0   
...     ...              ...              ...             ...   
22579     0                0                1               0   
22580     0                0                0               0   
22581     0                0                0               0   
22582     0                0                0               0   
22583     3                1                0               0   

       Facebook_Shared Income Education_Score   Age First_Interaction  \
0                    0   None            None  None         07-Jan-05   
1                    0      1              62    44         01-Sep-04   
2                    0   None            None  None         16-Sep-03   
3                    0   None            None  None         08-Nov-04   
4                    0   None            None  None         22-Jul-05   
...                ...    ...             ...   ...               ...   
22579                0      4            None    54         31-Jan-04   
22580                0   None            None  None         19-Jun-03   
22581                0   None            None  None         23-Jan-04   
22582                0      1            None    49         21-Feb-05   
22583                1      4              76    52         08-Nov-02   

      City_Type  Employer_Category  
0             B                NaN  
1             H  Software Industry  
2             D                NaN  
3           NaN                NaN  
4             E                NaN  
...         ...                ...  
22579         B         Technology  
22580       NaN                NaN  
22581         F                NaN  
22582         A          Transport  
22583         G        Real Estate  

[22584 rows x 18 columns]

In [705]:
train.corr()

Patient_ID  Health_Camp_ID      Var1      Var2      Var3  \
Patient_ID        1.000000        0.002648 -0.023396 -0.027426 -0.023258   
Health_Camp_ID    0.002648        1.000000  0.023319  0.015950  0.002644   
Var1             -0.023396        0.023319  1.000000  0.827286  0.335006   
Var2             -0.027426        0.015950  0.827286  1.000000  0.652482   
Var3             -0.023258        0.002644  0.335006  0.652482  1.000000   
Var4             -0.001952        0.017280  0.384708  0.346388  0.201331   
Var5             -0.018925        0.043284  0.764194  0.705389  0.372329   
outcome          -0.007473       -0.154757  0.048210  0.034520  0.012551   

                    Var4      Var5   outcome  
Patient_ID     -0.001952 -0.018925 -0.007473  
Health_Camp_ID  0.017280  0.043284 -0.154757  
Var1            0.384708  0.764194  0.048210  
Var2            0.346388  0.705389  0.034520  
Var3            0.201331  0.372329  0.012551  
Var4            1.000000  0.503231  0.034137  
Var5            0.503231  1.000000  0.064288  
outcome         0.034137  0.064288  1.000000

In [699]:
train[train["outcome"]==0].sort_values("Patient_ID") #485679
test["Var3"]

0    22577
1        7
Name: Var3, dtype: int64

In [124]:
train.shape
#(52694, 9)

X=train.drop(['Patient_ID', 'Health_Camp_ID', 'Registration_Date','outcome'],axis=1)
y=train["outcome"]

In [126]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
cross_val_score(log,X,y,cv=5,scoring='accuracy')

array([0.72843723, 0.728627  , 0.72881678, 0.7279628 , 0.72698804])

In [127]:
from lightgbm import LGBMClassifier
lgb=LGBMClassifier()
cross_val_score(lgb,X,y,cv=5,scoring='accuracy')

array([0.7299554 , 0.72653952, 0.73033495, 0.72739349, 0.72708294])

In [131]:
xtest=test.drop(['Patient_ID', 'Health_Camp_ID', 'Registration_Date'],axis=1)
model=lgb.fit(X,y)
preds=model.predict(xtest)

In [702]:
preds=test["Var3"]
preds.shape

(22584,)

In [704]:
sub = pd.DataFrame({"Patient_ID":test.Patient_ID})
sub["outcome"] =  preds
sub.to_csv("YN.csv", index=False)


In [148]:
train.nunique()

Patient_ID           24632
Health_Camp_ID          44
Registration_Date     1201
Var1                   120
Var2                    71
Var3                     2
Var4                     5
Var5                    30
outcome                  2
dtype: int64

In [155]:
X.shape,y.shape
y.value_counts()

0    38354
1    14340
Name: outcome, dtype: int64

In [158]:
pip install imblearn

In [160]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 2)
X_sm, y_sm = sm.fit_resample(X, y.ravel())


In [164]:
X_sm.shape,y_sm.shape
pd.Series(y_sm).value_counts()

(52694, 5)

In [168]:
cross_val_score(lgb,X_sm,pd.Series(y_sm),cv=5,scoring='accuracy')

array([0.5167514 , 0.52359536, 0.52463825, 0.52226061, 0.52023988])

In [189]:
#X["Var6"]=X.sum(axis=1)/5
X["Var5"].value_counts()
def v5(i):
    if i==0:
        return 4
    elif i<=8:
        return 2
    else:
        return 0
    
X["Var5"]=X["Var5"].apply(v5)   

In [201]:
def v1(i):
    if i==0:
        return 8
    elif i<=3:
        return 4
    elif i<=7:
        return 2
    else:
        return 0

In [203]:
X["Var1"]=X["Var1"].apply(v1)

In [207]:
X["Var2"].value_counts()
def v2(i):
    if i==0:
        return 2
    else:
        return 0
    
X["Var2"]=X["Var2"].apply(v2)

In [234]:
X.nunique()
X

Var1  Var2  Var3  Var4  Var5
0         8     2     0     0     4
1         8     2     0     0     4
2         8     2     0     0     4
3         8     2     0     0     4
4         8     2     0     0     4
...     ...   ...   ...   ...   ...
52689     8     2     0     0     4
52690     8     2     0     0     4
52691     8     2     0     0     4
52692     8     2     0     0     4
52693     8     2     0     0     4

[52694 rows x 5 columns]

In [235]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [243]:
log=LogisticRegression()
cross_val_score(rf,X,y,cv=5,scoring='accuracy')

array([0.72815258, 0.72815258, 0.72853212, 0.72748838, 0.72717783])

In [251]:
xtest["Var1"]=xtest["Var1"].apply(v1)
xtest["Var2"]=xtest["Var2"].apply(v2)
xtest["Var5"]=xtest["Var5"].apply(v5)
xtest.nunique()

Var1    4
Var2    2
Var3    2
Var4    5
Var5    3
dtype: int64

In [254]:
sm = SMOTE(random_state = 2)
X_sm, y_sm = sm.fit_resample(X, y.ravel())

In [255]:
model=rf.fit(X_sm,y_sm)
preds=model.predict(xtest)
sub = pd.DataFrame({"Patient_ID":test.Patient_ID})
sub["outcome"] =  preds
sub.to_csv("rf_sm.csv", index=False)

In [261]:
X2=train.drop(['Health_Camp_ID', 'Registration_Date','outcome'],axis=1)
y2=train["outcome"]

In [264]:
#pd.merge(train,test,on="Patient_ID",how="inner")
rf=RandomForestClassifier()
lgb=LGBMClassifier()
cross_val_score(lgb,X2,y2,cv=5,scoring='accuracy')

array([0.7299554 , 0.728627  , 0.72967075, 0.7279628 , 0.72622889])

In [269]:
xtest2=test.drop(['Health_Camp_ID', 'Registration_Date'],axis=1)

In [270]:
model=lgb.fit(X2,y2)
preds=model.predict(xtest2)
sub = pd.DataFrame({"Patient_ID":test.Patient_ID})
sub["outcome"] =  preds
sub.to_csv("lgb4.csv", index=False)

In [271]:
X3=train.drop(['Registration_Date','outcome'],axis=1)
y3=train["outcome"]
xtest3=test.drop(['Registration_Date'],axis=1)

In [272]:
#pd.merge(train,test,on="Patient_ID",how="inner")
rf=RandomForestClassifier()
lgb=LGBMClassifier()
cross_val_score(lgb,X3,y3,cv=5,scoring='accuracy')

array([0.79912705, 0.79599583, 0.79609071, 0.80178385, 0.7954071 ])

In [273]:
model=lgb.fit(X3,y3)
preds=model.predict(xtest3)
sub = pd.DataFrame({"Patient_ID":test.Patient_ID})
sub["outcome"] =  preds
sub.to_csv("lgb5.csv", index=False)

In [294]:
hc=dict(zip(list(train.sort_values("Patient_ID").groupby("Health_Camp_ID")["outcome"].sum().index),
list(train.sort_values("Patient_ID").groupby("Health_Camp_ID")["outcome"].sum().values)))
#test.sort_values("Patient_ID")
pc=dict(zip(list(train.sort_values("Patient_ID").groupby("Patient_ID")["outcome"].sum().index),
list(train.sort_values("Patient_ID").groupby("Patient_ID")["outcome"].sum().values)))


In [298]:
train["hc"]=train["Health_Camp_ID"].map(hc)
train["pc"]=train["Patient_ID"].map(pc)
train.head()


Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5  \
0      526927            6570          14/05/05     0     0     0     0     0   
1      510379            6534          26/05/06     0     0     0     0     0   
2      520968            6557          07/01/04     0     0     0     0     0   
3      507625            6535          12/02/04     0     0     0     0     0   
4      502611            6581          14/03/04     0     0     0     0     0   

   outcome    hc  pc  
0        0   196   0  
1        1  1770   1  
2        1    24   1  
3        0   180   0  
4        0    65   0

In [305]:
test["hc"]=test["Health_Camp_ID"].map(hc)
test["pc"]=test["Patient_ID"].map(pc)
test.head()
test["pc"]=test["pc"].fillna(0)

In [311]:
train.head()

Patient_ID  Health_Camp_ID Registration_Date  Var1  Var2  Var3  Var4  Var5  \
0      526927            6570          14/05/05     0     0     0     0     0   
1      510379            6534          26/05/06     0     0     0     0     0   
2      520968            6557          07/01/04     0     0     0     0     0   
3      507625            6535          12/02/04     0     0     0     0     0   
4      502611            6581          14/03/04     0     0     0     0     0   

   outcome    hc  pc  
0        0   196   0  
1        1  1770   1  
2        1    24   1  
3        0   180   0  
4        0    65   0

In [337]:
train["Registration_Date"]=train.Registration_Date.fillna(train.Registration_Date.mode()[0])
test["Registration_Date"]=test.Registration_Date.fillna(test.Registration_Date.mode()[0])

In [350]:
rdtr=dict(zip(list(train.Registration_Date.value_counts().index),list(train.Registration_Date.value_counts().values)))
train["Registration_Date"]=train["Registration_Date"].map(rdtr)
rdts=dict(zip(list(test.Registration_Date.value_counts().index),list(test.Registration_Date.value_counts().values)))
test["Registration_Date"]=test["Registration_Date"].map(rdts)

In [351]:
X4=train.drop(['outcome','hc','pc'],axis=1)
y4=train["outcome"]
xtest4=test.drop(['hc','pc'],axis=1)

In [352]:
lgb=LGBMClassifier()
cross_val_score(lgb,X4,y4,cv=5,scoring='accuracy')

array([0.80842585, 0.80984913, 0.80595882, 0.81753487, 0.80688935])

In [353]:
model=lgb.fit(X4,y4)
preds=model.predict(xtest4)
sub = pd.DataFrame({"Patient_ID":test.Patient_ID})
sub["outcome"] =  preds
sub.to_csv("lgb11.csv", index=False)

In [448]:
train[train["Patient_ID"]==507518]["outcome"].mode()[0]
hc_details.head()

Health_Camp_ID Camp_Start_Date Camp_End_Date Category1 Category2  Category3
0            6560       16-Aug-03     20-Aug-03     First         B          2
1            6530       16-Aug-03     28-Oct-03     First         C          2
2            6544       03-Nov-03     15-Nov-03     First         F          1
3            6585       22-Nov-03     05-Dec-03     First         E          2
4            6561       30-Nov-03     18-Dec-03     First         E          1

In [454]:
shc.head()
train.sort_values("Patient_ID")
shc.sort_values("Patient_ID")
tph=train.merge(patient,on=["Patient_ID"],how="outer").merge(hc_details,on="Health_Camp_ID",how="outer")
tph123=tph.merge(fhc,on=["Patient_ID","Health_Camp_ID"],how="outer").merge(shc,on=["Patient_ID","Health_Camp_ID"],how="outer").merge(thc,on=["Patient_ID","Health_Camp_ID"],how="outer")

In [511]:
df=tph123.sort_values(["Patient_ID","outcome","Health_Camp_ID"]).drop("Unnamed: 4",axis=1).ffill().bfill()
df=df.drop(["Registration_Date","Camp_Start_Date","Camp_End_Date","hc","pc","First_Interaction"],axis=1)
cat=pd.get_dummies(df[['City_Type','Employer_Category', 'Category1', 'Category2', 'Category3']],drop_first=True)
df.columns

Index(['Patient_ID', 'Health_Camp_ID', 'Var1', 'Var2', 'Var3', 'Var4', 'Var5',
       'outcome', 'Online_Follower', 'LinkedIn_Shared', 'Twitter_Shared',
       'Facebook_Shared', 'Income', 'Education_Score', 'Age', 'City_Type',
       'Employer_Category', 'Category1', 'Category2', 'Category3', 'Donation',
       'Health_Score', 'Health Score', 'Number_of_stall_visited',
       'Last_Stall_Visited_Number'],
      dtype='object')

In [513]:
df=df.drop(['City_Type','Employer_Category', 'Category1', 'Category2', 'Category3'],axis=1)

In [515]:
df1=pd.concat([df,cat],axis=1)

In [521]:
df1=df1.replace("None",0)


In [522]:
tpht=test.merge(patient,on=["Patient_ID"],how="outer").merge(hc_details,on="Health_Camp_ID",how="outer")
tph123t=tpht.merge(fhc,on=["Patient_ID","Health_Camp_ID"],how="outer").merge(shc,on=["Patient_ID","Health_Camp_ID"],how="outer").merge(thc,on=["Patient_ID","Health_Camp_ID"],how="outer")

In [524]:
dft=tph123t.sort_values(["Patient_ID","Health_Camp_ID"]).drop("Unnamed: 4",axis=1).ffill().bfill()
dft=dft.drop(["Registration_Date","Camp_Start_Date","Camp_End_Date","hc","pc","First_Interaction"],axis=1)
catt=pd.get_dummies(dft[['City_Type','Employer_Category', 'Category1', 'Category2', 'Category3']],drop_first=True)
dft.columns

Index(['Patient_ID', 'Health_Camp_ID', 'Var1', 'Var2', 'Var3', 'Var4', 'Var5',
       'Online_Follower', 'LinkedIn_Shared', 'Twitter_Shared',
       'Facebook_Shared', 'Income', 'Education_Score', 'Age', 'City_Type',
       'Employer_Category', 'Category1', 'Category2', 'Category3', 'Donation',
       'Health_Score', 'Health Score', 'Number_of_stall_visited',
       'Last_Stall_Visited_Number'],
      dtype='object')

In [526]:
dft=dft.drop(['City_Type','Employer_Category', 'Category1', 'Category2', 'Category3'],axis=1)
dft1=pd.concat([dft,catt],axis=1)


In [527]:
dft1=dft1.replace("None",0)

In [537]:
df1["Income"]=df1["Income"].astype(float)
df1["Education_Score"]=df1["Education_Score"].astype(float)
df1["Age"]=df1["Age"].astype(float)


In [545]:
df1=df1.rename(columns={"Health_Score":"HS"})

In [539]:
dft1["Income"]=dft1["Income"].astype(float)
dft1["Education_Score"]=dft1["Education_Score"].astype(float)
dft1["Age"]=dft1["Age"].astype(float)

In [546]:
dft1=dft1.rename(columns={"Health_Score":"HS"})

In [547]:
X5=df1.drop("outcome",axis=1)
y5=df1["outcome"]

Patient_ID  Health_Camp_ID  Var1  Var2  Var3  Var4  Var5  \
60724    485678.0          6555.0   0.0   0.0   0.0   0.0   0.0   
39546    485679.0          6555.0   0.0   0.0   0.0   0.0   0.0   
27861    485679.0          6578.0   0.0   0.0   0.0   0.0   0.0   
58216    485680.0          6578.0   0.0   0.0   0.0   0.0   0.0   
16211    485681.0          6580.0   0.0   0.0   0.0   0.0   0.0   

       Online_Follower  LinkedIn_Shared  Twitter_Shared  ...  \
60724              0.0              0.0             0.0  ...   
39546              0.0              0.0             0.0  ...   
27861              0.0              0.0             0.0  ...   
58216              0.0              0.0             0.0  ...   
16211              0.0              0.0             0.0  ...   

       Employer_Category_Telecom Employer_Category_Transport Category1_Second  \
60724                          0                           0                1   
39546                          0                           0                1   
27861                          0                           0                0   
58216                          0                           0                0   
16211                          0                           0                0   

      Category1_Third  Category2_B  Category2_C  Category2_D  Category2_E  \
60724               0            0            0            0            0   
39546               0            0            0            0            0   
27861               1            0            0            0            0   
58216               1            0            0            0            0   
16211               0            0            0            0            1   

       Category2_F  Category2_G  
60724            0            0  
39546            0            0  
27861            0            1  
58216            0            1  
16211            0            0  

[5 rows x 49 columns]

In [548]:
lgb=LGBMClassifier()
cross_val_score(lgb,X5,y5,cv=5,scoring='accuracy')

array([0.69347887, 0.8039352 , 0.80671626, 0.78293819, 0.8005284 ])

In [552]:
model=lgb.fit(X5,y5)
preds=model.predict(dft1)
sub = pd.DataFrame({"Patient_ID":dft1.Patient_ID})
sub["outcome"] =  preds
sub.to_csv("comp1.csv", index=False)

In [578]:
#pd.merge(ss,sub,on="Patient_ID",how="left")
sub=sub[sub.duplicated(["Patient_ID","outcome"])]


In [583]:
#sub[sub.duplicated(["Patient_ID"])]
sub=sub.drop_duplicates("Patient_ID")

In [593]:
fd=ss.merge(sub,on=["Patient_ID"],how="left")
fd["outcome_y"]=fd["outcome_y"].fillna(fd["outcome_x"])
fd.drop("outcome_x",axis=1,inplace=True)

In [596]:
fd=fd.rename(columns={"outcome_y":"outcome"})

In [597]:
fd.to_csv("fd1.csv",index=False)

In [664]:
test6=test.sort_values("Patient_ID").merge(patient.sort_values("Patient_ID")).drop(['Registration_Date','hc','pc','Income','Education_Score','Age','First_Interaction', 'City_Type','Employer_Category'],axis=1)
train6=train.sort_values("Patient_ID").merge(patient.sort_values("Patient_ID")).drop(['Registration_Date','hc','pc','Income','Education_Score', 'Age', 'First_Interaction', 'City_Type','Employer_Category'],axis=1)

In [665]:
#test6.merge(train,on="Health_Camp_ID")
train=train.sort_values("Health_Camp_ID").reset_index()
test6=test6.sort_values("Health_Camp_ID").reset_index()



In [670]:
test6.drop("index",axis=1,inplace=True)
train.drop("index",axis=1,inplace=True)

In [675]:
train

Patient_ID  Health_Camp_ID  Registration_Date  Var1  Var2  Var3  Var4  \
0          522358            6523                125     0     0     0     0   
1          489313            6523                 99     0     0     0     0   
2          528191            6523                 41     0     0     0     0   
3          514061            6523                 58     0     0     0     0   
4          496617            6523                139     0     0     0     0   
...           ...             ...                ...   ...   ...   ...   ...   
52689      506395            6587                 63     0     0     0     0   
52690      489434            6587                116     0     0     0     0   
52691      505965            6587                116     0     0     0     0   
52692      519024            6587                 86     0     0     0     0   
52693      525691            6587                116     0     0     0     0   

       Var5  outcome    hc  pc  
0         0        1  1037   3  
1         0        1  1037   5  
2         0        1  1037   2  
3         0        0  1037   0  
4         0        1  1037   2  
...     ...      ...   ...  ..  
52689     0        1    22   1  
52690     0        1    22   1  
52691     0        1    22   1  
52692     0        0    22   0  
52693     0        0    22   0  

[52694 rows x 11 columns]

In [632]:
X6=train6.drop("outcome",axis=1)
y6=train6["outcome"]